### ISSUE TITLE
Menu flickers when clicked

### ISSUE THREAD

**Issue by sennewood** [zuramai/voler#10]
In the demo (https://zuramai.github.io/voler/dist/index.html) the menu icons and texts flickers, when I click on a entry. It looks like the space between them will be 0 for a short time.

**Comment by zuramai** [comment]
Can you give any screenshot?

**Comment by sennewood** [comment]
The link delivers a 404 error ... so I can't ^^

**Comment by zuramai** [comment]
I'm sorry the link was changed to https://zuramai.github.io/voler

**Comment by sennewood** [comment]
![ezgif com-optimize](https://user-images.githubusercontent.com/406414/105326155-bcddae00-5bcd-11eb-9b97-15eeb6df74ee.gif)

**Comment by zuramai** [comment]
Maybe that's seems like a flicker, but it's not. 
When you click the submenu, it will reset the hover state (which is moving the menu) and then the submenu is moving again because you still hovering on it. 

and the icon is reloaded too so it looks like a flicker.

**Comment by sennewood** [comment]
Call it how you prefer :)
If it works as intended, close the issue.
