### ISSUE TITLE
Regarding the Voler Admin Design

### ISSUE THREAD

**Issue by pixinvent** [zuramai/voler#15]
Ajay here, Nice to e-meet you.

Please find the attached images for your reference.

Overall UI (image-1): Voler overall template look & feel has Frest Admin (https://themeforest.net/item/frest-clean-minimal-bootstrap-admin-dashboard-template/24656841). UI/UX touch, compare the buttons, inputs, modal & many more, etc.. 

We insist you change the UI or remove their repository asap (in 24hrs), else we will raise DMCA takedown notice on GitHub for this violation. Make sure you have your own design idea which has a significant difference in comparison to Frest.

Thanks,

![Screenshot 2021-02-24 at 3 24 12 PM](https://user-images.githubusercontent.com/26670210/108983349-c8ccfc00-76b4-11eb-8ae7-65edd62d04db.png)
![Screenshot 2021-02-24 at 3 23 40 PM](https://user-images.githubusercontent.com/26670210/108983358-cb2f5600-76b4-11eb-960e-5910f753da6c.png)
![Screenshot 2021-02-24 at 3 23 10 PM](https://user-images.githubusercontent.com/26670210/108983363-ccf91980-76b4-11eb-8f98-6354404b881f.png)

**Comment by zuramai** [comment]
Thanks for noticing me! I will update soon
