### ISSUE TITLE
Bug on sidebar dropdown

### ISSUE THREAD

**Issue by dimassubaktian** [zuramai/voler#7]
Bug on sidebar dropdown only show 12 item and can't show more than it. under progress item
![image](https://user-images.githubusercontent.com/33174740/95416018-edba1000-095b-11eb-8ac6-7cb46d8c252c.png)

**Comment by superawdi** [comment]
Simply change the max-height property to something like 2500px in .submenu.active class in css.

**Comment by superawdi** [comment]
> Bug on sidebar dropdown only show 12 item and can't show more than it. under progress item
> ![image](https://user-images.githubusercontent.com/33174740/95416018-edba1000-095b-11eb-8ac6-7cb46d8c252c.png)

Simply change the max-height property to something like 2500px in .submenu.active class in css.
![2020-11-13 08_02_17-Dashboard - Voler Admin Dashboard](https://user-images.githubusercontent.com/45320789/99075182-0c2cb000-2587-11eb-9694-6994c428f9c2.png)
